using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SampleReflection
{
    
    public class EcApphDetail
    {
        public string l_lastdecision { get; set; }
        public int l_apptotal { get; set; }
        public int l_timesincelastapp { get; set; }
        public DateTime l_lastdeclineddate { get; set; }
        public string l_lastdeclinedproduct { get; set; }
        public string l_lastdeclinedreason { get; set; }
        public int l_declinedtotal { get; set; }
        public int l_declinedkktotal { get; set; }
        public DateTime l_lastdeclinedappdt_1 { get; set; }
        public DateTime l_lastdeclinedappdt_2 { get; set; }
        public DateTime l_lastdeclinedappdt_3 { get; set; }
        public DateTime l_lastdeclinedappdt_4 { get; set; }
        public DateTime l_lastdeclinedappdt_5 { get; set; }
        public DateTime l_lastdeclinedappdt_6 { get; set; }
        public DateTime l_lastdeclinedappdt_7 { get; set; }
        public DateTime l_lastdeclinedappdt_8 { get; set; }
        public DateTime l_lastdeclinedappdt_9 { get; set; }
        public DateTime l_lastdeclinedappdt_10 { get; set; }
        public string l_lastdecreasoncode_1 { get; set; }
        public string l_lastdecreasoncode_2 { get; set; }
        public string l_lastdecreasoncode_3 { get; set; }
        public string l_lastdecreasoncode_4 { get; set; }
        public string l_lastdecreasoncode_5 { get; set; }
        public string l_lastdecreasoncode_6 { get; set; }
        public string l_lastdecreasoncode_7 { get; set; }
        public string l_lastdecreasoncode_8 { get; set; }
        public string l_lastdecreasoncode_9 { get; set; }
        public string l_lastdecreasoncode_10 { get; set; }
        public DateTime l_lastdeclinedappdate { get; set; }
        public int l_declinedkmhlimitincpermanent { get; set; }
        public int l_declinedkmhtotal { get; set; }
        public int l_declinedapp_1 { get; set; }
        public int l_declinedapp_2 { get; set; }
        public int l_declinedapp_3 { get; set; }
        public int l_declinedapp_4 { get; set; }
        public int l_declinedapp_5 { get; set; }
        public int l_declinedapp_6 { get; set; }
        public int l_declinedapp_7 { get; set; }
        public int l_declinedapp_8 { get; set; }
        public int l_declinedapp_9 { get; set; }
        public int l_declinedapp_10 { get; set; }
        public int l_last12monthdeclinedapp_1 { get; set; }
        public int l_last12monthdeclinedapp_2 { get; set; }
        public int l_last12monthdeclinedapp_3 { get; set; }
        public int l_last12monthdeclinedapp_4 { get; set; }
        public int l_last12monthdeclinedapp_5 { get; set; }
        public int l_last12monthdeclinedapp_6 { get; set; }
        public int l_last12monthdeclinedapp_7 { get; set; }
        public int l_last12monthdeclinedapp_8 { get; set; }
        public int l_last12monthdeclinedapp_9 { get; set; }
        public int l_last12monthdeclinedapp_10 { get; set; }
        public int l_last3monthdeclinedapp_1 { get; set; }
        public int l_last3monthdeclinedapp_2 { get; set; }
        public int l_last3monthdeclinedapp_3 { get; set; }
        public int l_last3monthdeclinedapp_4 { get; set; }
        public int l_last3monthdeclinedapp_5 { get; set; }
        public int l_last3monthdeclinedapp_6 { get; set; }
        public int l_last3monthdeclinedapp_7 { get; set; }
        public int l_last3monthdeclinedapp_8 { get; set; }
        public int l_last3monthdeclinedapp_9 { get; set; }
        public int l_last3monthdeclinedapp_10 { get; set; }
        public int l_last6monthdeclinedapp_1 { get; set; }
        public int l_last6monthdeclinedapp_2 { get; set; }
        public int l_last6monthdeclinedapp_3 { get; set; }
        public int l_last6monthdeclinedapp_4 { get; set; }
        public int l_last6monthdeclinedapp_5 { get; set; }
        public int l_last6monthdeclinedapp_6 { get; set; }
        public int l_last6monthdeclinedapp_7 { get; set; }
        public int l_last6monthdeclinedapp_8 { get; set; }
        public int l_last6monthdeclinedapp_9 { get; set; }
        public int l_last6monthdeclinedapp_10 { get; set; }
        public int l_lastmonthdeclinedapp_1 { get; set; }
        public int l_lastmonthdeclinedapp_2 { get; set; }
        public int l_lastmonthdeclinedapp_3 { get; set; }
        public int l_lastmonthdeclinedapp_4 { get; set; }
        public int l_lastmonthdeclinedapp_5 { get; set; }
        public int l_lastmonthdeclinedapp_6 { get; set; }
        public int l_lastmonthdeclinedapp_7 { get; set; }
        public int l_lastmonthdeclinedapp_8 { get; set; }
        public int l_lastmonthdeclinedapp_9 { get; set; }
        public int l_lastmonthdeclinedapp_10 { get; set; }
        public int l_pendingkklimitincpermanent { get; set; }
        public int l_pendingkmhlimitdec { get; set; }
        public int l_pendingkmhlimitincpermanent { get; set; }
        public int l_pendingkmhtotal { get; set; }
        public int l_pendingappl_1 { get; set; }
        public int l_pendingappl_2 { get; set; }
        public int l_pendingappl_3 { get; set; }
        public int l_pendingappl_4 { get; set; }
        public int l_pendingappl_5 { get; set; }
        public int l_pendingappl_6 { get; set; }
        public int l_pendingappl_7 { get; set; }
        public int l_pendingappl_8 { get; set; }
        public int l_pendingappl_9 { get; set; }
        public int l_pendingappl_10 { get; set; }
        public DateTime l_lastappdate_1 { get; set; }
        public DateTime l_lastappdate_2 { get; set; }
        public DateTime l_lastappdate_3 { get; set; }
        public DateTime l_lastappdate_4 { get; set; }
        public DateTime l_lastappdate_5 { get; set; }
        public DateTime l_lastappdate_6 { get; set; }
        public DateTime l_lastappdate_7 { get; set; }
        public DateTime l_lastappdate_8 { get; set; }
        public DateTime l_lastappdate_9 { get; set; }
        public DateTime l_lastappdate_10 { get; set; }
        public string l_lastdecisionapp_1 { get; set; }
        public string l_lastdecisionapp_2 { get; set; }
        public string l_lastdecisionapp_3 { get; set; }
        public string l_lastdecisionapp_4 { get; set; }
        public string l_lastdecisionapp_5 { get; set; }
        public string l_lastdecisionapp_6 { get; set; }
        public string l_lastdecisionapp_7 { get; set; }
        public string l_lastdecisionapp_8 { get; set; }
        public string l_lastdecisionapp_9 { get; set; }
        public string l_lastdecisionapp_10 { get; set; }
        public int l_totalapp_1 { get; set; }
        public int l_totalapp_2 { get; set; }
        public int l_totalapp_3 { get; set; }
        public int l_totalapp_4 { get; set; }
        public int l_totalapp_5 { get; set; }
        public int l_totalapp_6 { get; set; }
        public int l_totalapp_7 { get; set; }
        public int l_totalapp_8 { get; set; }
        public int l_totalapp_9 { get; set; }
        public int l_totalapp_10 { get; set; }
        public int l_last12monthtotalapp_1 { get; set; }
        public int l_last12monthtotalapp_2 { get; set; }
        public int l_last12monthtotalapp_3 { get; set; }
        public int l_last12monthtotalapp_4 { get; set; }
        public int l_last12monthtotalapp_5 { get; set; }
        public int l_last12monthtotalapp_6 { get; set; }
        public int l_last12monthtotalapp_7 { get; set; }
        public int l_last12monthtotalapp_8 { get; set; }
        public int l_last12monthtotalapp_9 { get; set; }
        public int l_last12monthtotalapp_10 { get; set; }
        public int l_last3monthtotalapp_1 { get; set; }
        public int l_last3monthtotalapp_2 { get; set; }
        public int l_last3monthtotalapp_3 { get; set; }
        public int l_last3monthtotalapp_4 { get; set; }
        public int l_last3monthtotalapp_5 { get; set; }
        public int l_last3monthtotalapp_6 { get; set; }
        public int l_last3monthtotalapp_7 { get; set; }
        public int l_last3monthtotalapp_8 { get; set; }
        public int l_last3monthtotalapp_9 { get; set; }
        public int l_last3monthtotalapp_10 { get; set; }
        public int l_last6monthtotalapp_1 { get; set; }
        public int l_last6monthtotalapp_2 { get; set; }
        public int l_last6monthtotalapp_3 { get; set; }
        public int l_last6monthtotalapp_4 { get; set; }
        public int l_last6monthtotalapp_5 { get; set; }
        public int l_last6monthtotalapp_6 { get; set; }
        public int l_last6monthtotalapp_7 { get; set; }
        public int l_last6monthtotalapp_8 { get; set; }
        public int l_last6monthtotalapp_9 { get; set; }
        public int l_last6monthtotalapp_10 { get; set; }
        public int l_lastmonthtotalapp_1 { get; set; }
        public int l_lastmonthtotalapp_2 { get; set; }
        public int l_lastmonthtotalapp_3 { get; set; }
        public int l_lastmonthtotalapp_4 { get; set; }
        public int l_lastmonthtotalapp_5 { get; set; }
        public int l_lastmonthtotalapp_6 { get; set; }
        public int l_lastmonthtotalapp_7 { get; set; }
        public int l_lastmonthtotalapp_8 { get; set; }
        public int l_lastmonthtotalapp_9 { get; set; }
        public int l_lastmonthtotalapp_10 { get; set; }
        public DateTime l_lastacceptappdate_1 { get; set; }
        public DateTime l_lastacceptappdate_2 { get; set; }
        public DateTime l_lastacceptappdate_3 { get; set; }
        public DateTime l_lastacceptappdate_4 { get; set; }
        public DateTime l_lastacceptappdate_5 { get; set; }
        public DateTime l_lastacceptappdate_6 { get; set; }
        public DateTime l_lastacceptappdate_7 { get; set; }
        public DateTime l_lastacceptappdate_8 { get; set; }
        public DateTime l_lastacceptappdate_9 { get; set; }
        public DateTime l_lastacceptappdate_10 { get; set; }
        public int l_acceptapp_1 { get; set; }
        public int l_acceptapp_2 { get; set; }
        public int l_acceptapp_3 { get; set; }
        public int l_acceptapp_4 { get; set; }
        public int l_acceptapp_5 { get; set; }
        public int l_acceptapp_6 { get; set; }
        public int l_acceptapp_7 { get; set; }
        public int l_acceptapp_8 { get; set; }
        public int l_acceptapp_9 { get; set; }
        public int l_acceptapp_10 { get; set; }
        public int l_last12monthacceptapp_1 { get; set; }
        public int l_last12monthacceptapp_2 { get; set; }
        public int l_last12monthacceptapp_3 { get; set; }
        public int l_last12monthacceptapp_4 { get; set; }
        public int l_last12monthacceptapp_5 { get; set; }
        public int l_last12monthacceptapp_6 { get; set; }
        public int l_last12monthacceptapp_7 { get; set; }
        public int l_last12monthacceptapp_8 { get; set; }
        public int l_last12monthacceptapp_9 { get; set; }
        public int l_last12monthacceptapp_10 { get; set; }
        public int l_last3monthacceptapp_1 { get; set; }
        public int l_last3monthacceptapp_2 { get; set; }
        public int l_last3monthacceptapp_3 { get; set; }
        public int l_last3monthacceptapp_4 { get; set; }
        public int l_last3monthacceptapp_5 { get; set; }
        public int l_last3monthacceptapp_6 { get; set; }
        public int l_last3monthacceptapp_7 { get; set; }
        public int l_last3monthacceptapp_8 { get; set; }
        public int l_last3monthacceptapp_9 { get; set; }
        public int l_last3monthacceptapp_10 { get; set; }
        public int l_last6monthacceptapp_1 { get; set; }
        public int l_last6monthacceptapp_2 { get; set; }
        public int l_last6monthacceptapp_3 { get; set; }
        public int l_last6monthacceptapp_4 { get; set; }
        public int l_last6monthacceptapp_5 { get; set; }
        public int l_last6monthacceptapp_6 { get; set; }
        public int l_last6monthacceptapp_7 { get; set; }
        public int l_last6monthacceptapp_8 { get; set; }
        public int l_last6monthacceptapp_9 { get; set; }
        public int l_last6monthacceptapp_10 { get; set; }
        public int l_lastmonthacceptapp_1 { get; set; }
        public int l_lastmonthacceptapp_2 { get; set; }
        public int l_lastmonthacceptapp_3 { get; set; }
        public int l_lastmonthacceptapp_4 { get; set; }
        public int l_lastmonthacceptapp_5 { get; set; }
        public int l_lastmonthacceptapp_6 { get; set; }
        public int l_lastmonthacceptapp_7 { get; set; }
        public int l_lastmonthacceptapp_8 { get; set; }
        public int l_lastmonthacceptapp_9 { get; set; }
        public int l_lastmonthacceptapp_10 { get; set; }
    }
}